name: Update NOS News

on:
  schedule:
    # Elke 5 minuten
    - cron: '*/5 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser pytz

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Forceer een wijziging door de huidige tijd in een hulpbestand te zetten
          date > last_run.txt
          
          git add news.json last_run.txt
          
          # We committen ALTIJD omdat last_run.txt sowieso veranderd is
          git commit -m "Automatische nieuws update: $(date)"
          git push
