name: KWC News Auto Update

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install libs
        run: pip install feedparser pytz

      - name: Execute script
        run: python fetch_news.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "KWC Automation"
          git config --global user.email "automation@kustwacht.nl"
          date > last_run.txt
          git add news.json last_run.txt
          git commit -m "System: News Feed Updated $(date)" || echo "No changes to commit"
          git push
